### ISSUE TITLE
Error when running on CPU

### ISSUE THREAD

**Issue by inchiosa** [microsoft/project-azua#1]
I observed this error when running on CPU:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I made this change in project-azua/azua/models/torch_model.py and now it works:
        # model.load_state_dict(torch.load(model_path))
        model.load_state_dict(torch.load(model_path, map_location=torch.device(torch_device)))

**Comment by makukl** [comment]
Thank you for reporting the issue, and providing the fix. The fix has been included in the https://github.com/microsoft/project-azua/commit/e33398f1de28eb9900e04d1ecd7d19d825cdc483 commit (currently part of the master branch)
