### ISSUE TITLE
Model of GINA

### ISSUE THREAD

**Issue by Sam1224** [microsoft/project-azua#2]
Hi, has the GINA model (Identifiable Generative Models for Missing Not at Random Data Imputation) already been released? I cannot find it in this repository.

**Comment by LaurantChao** [comment]
Hi Sam, yes it is released, please refer to section 5.4 in the Readme.

**Comment by Sam1224** [comment]
> Hi Sam, yes it is released, please refer to section 5.4 in the Readme.

Ok, thank you so much.

**Comment by zhangtj1996** [comment]
Has anyone reproduced the results in the GINA paper? 
I cannot find the details about the synthetic example in the paper.
