### ISSUE TITLE
Error with running model CoRGi

### ISSUE THREAD

**Issue by nyongja** [microsoft/project-azua#3]
When I run the CoRGi model with the Goodreads dataset, there are several errors.
I made a goodreads dataset with this code, 'research_experiences/GNN/create_goodreads_dataset.py'.

First, in line 325 of the graph_neural_network.py, an assertion occurs because the data format is not GraphData. 
So I tried to use the to_graph function in Dataset Class. 

And in 842 of the graph_neural_network.py, AttributeError occurs because there is no x attribute in the data. 

`AttributeError: 'Dataset' object does not have attribute 'x'.`

How do I solve this?

**Comment by nyongja** [comment]
It was solved by changing the dataet_format to gnn_csv!  Thank you

**Comment by nyongja** [comment]
How can I change the sentences.csv to sentences_array.npy in goodreads dataset?

**Comment by jyscardioid** [comment]
> How can I change the sentences.csv to sentences_array.npy in goodreads dataset?

Assuming you already have `sentences.csv`,
you can run `transform_sentence_csv_to_list()` in `research_experiments/eedi/sentence_to_embedding.py`.
It reads the csv file using `pd.read_csv` and makes it into an array.

**Comment by nyongja** [comment]
Thank you for your answer 👍
