### ISSUE TITLE
run_experiment: ‘Provide’ object has no attribute ‘metrics_logger’

### ISSUE THREAD

**Issue by yashua-ovando** [microsoft/project-azua#5]
### ISSUE
**When running `python run_experiment.py boston -mt pvae -i -a eddi rand` the program fails@ line 216-218 in run_experiment.py**

lines 216-218:
```
kwargs_file = azua_context.aml_step(run_aggregation, pipeline_creation_mode)(
        input_dirs=input_dirs, 
	output_dir=models_dir, 
	experiment_name=experiment_name, 
	aml_tags=aml_tags
)
```
#### Error message
  File “../project-azua/azua/experiment/run_aggregation.py", line 16, in run_aggregation 
     metrics_logger = azua_context.metrics_logger()
AttributeError: ‘Provide’ object has no attribute ‘metrics_logger’

The error refers to this function:
```
def run_aggregation(
    input_dirs: List[str],
    output_dir: str,
    experiment_name: str,
    aml_tags=Dict[str, Any],
    azua_context: AzuaContext = Provide[AzuaContext],
) 
```

### SOLUTION
To fix the issue I included the azua_context param in lines 216-218:
```
kwargs_file = azua_context.aml_step(run_aggregation, pipeline_creation_mode)(
        input_dirs=input_dirs, 
	output_dir=models_dir, 
	experiment_name=experiment_name, 
	aml_tags=aml_tags,
	azua_context=azua_context
)
```
Ran successfully.

**Comment by agrinh** [comment]
@yashua-ovando thanks for raising the issue and for your patience!

I've been unable to reproduce your issue. Have you done any other edits or are you really running that exact command on the current master branch of this repo? Looks like you should never get to :216-218 unless you overwrite the `AzuaContext` to provide a pipeline, in which case you'd be in `pipeline_creation_mode`.

If you are trying to run with a pipeline, you may also need to do `AzuaContext().wire(packages=[azua])` somewhere to wire the dependency injection.
