### ISSUE TITLE
Import Error: Attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ReetKaur15** [microsoft/project-azua#8]
Hi,

When I try to run the run_experiment.py script. It shows the following error.

File "run_experiment.py", line 29, in <module>
    from . import models as amodels
ImportError: attempted relative import with no known parent package.

Please look into this and suggest something. 

Many Thanks and Regards

**Comment by confoundry** [comment]
Hi, from the root run `python -m azua.run_experiment`

**Comment by ReetKaur15** [comment]
@confoundry , Thanks it is working. :)
